### ISSUE TITLE
Support for CommonJS modules?

### ISSUE THREAD

**Issue by r1sc** [Microsoft/PowerBI-visuals-sampleUsingExternalLibraries#1]
This is great, but I can't get it to work with libraries packaged as CommonJS modules. 
For example three.js:

```
npm install --save three
```

tsconfig.json:
```
"files": [
    "node_modules/three/build/three.min.js",
    ...
]
```
Results in error "THREE is not defined".

**Comment by johnyesberg** [comment]
Hi @r1sc , any hints about how you fixed this?

**Comment by r1sc** [comment]
Yes I ended up creating a script "windowfixer.js" that simply does:
```this.window.THREE = window.THREE;```

Reference this in your tsconfig somewhere after three.js but before your main visual is loaded.

**Comment by johnyesberg** [comment]
Thanks @r1sc - just what I needed!
